In [2]:
import os
import pandas as pd
import numpy as np

result_dir = "/home/ubuntu/tt_assignment/yolov5/runs/detect/exp12/labels"

In [18]:
label_files = os.listdir(result_dir)

for label_file in label_files:
    anns = []
    label_path = os.path.join(result_dir, label_file)
    f = open(label_path, "r")
    lines = f.readlines()
    for line in lines:
        ann = line.strip("\n").split(" ")
        anns.append(ann)
    anns = np.array(anns, np.float32)
    area = np.multiply(anns[:,3], anns[:,4])
    if anns.shape[0] > 1:
        ##case 1 
            #  all "Other-class 0"
            #  all "lenin-class 1"
            #  all "Atartuk-class 2"
        ### Take larger one        
        cls_ids = anns[:,0]
        if len(np.unique(cls_ids)) == 1:
            print(cls_ids)
            large_idx = np.argmax(area)
            print(anns[large_idx])
        
        ## case 2 
            ##Lenin
            ##Atartuk
            ##other
        #take larger of lenin and atartuk
        
        ## case 3 
            ##Lenin
            ##other
        #take lenin

        ## case 4 
            ##atarktuk
            ##other
        #take atartuk

        ##case 5 
            ## other

[0. 0. 0.]
[0.        0.509194  0.162587  0.042994  0.0757576]
[0. 0. 0.]
[0.        0.411569  0.503989  0.0571809 0.0398936]
[0. 0. 0.]
[0.        0.436027  0.245532  0.030821  0.0528361]
[0. 0.]
[0.        0.653441  0.370802  0.109551  0.0974813]
[0. 0. 0.]
[0.       0.693991 0.277778 0.126133 0.247863]
[0. 0.]
[0.        0.511082  0.137633  0.0221631 0.0385638]
[0. 0. 0. 0. 0. 0. 0.]
[0.        0.0766844 0.340093  0.072695  0.140293 ]
[0. 0.]
[0.        0.518949  0.192598  0.0525266 0.0421099]
[0. 0.]
[0.        0.675975  0.174867  0.0975177 0.166223 ]
[0. 0. 0. 0. 0. 0. 0.]
[0.        0.59059   0.0939832 0.0976124 0.0713619]
[0. 0.]
[0.        0.449246  0.178191  0.0332447 0.0611702]
[0. 0.]
[0.        0.407318  0.270967  0.0290242 0.0413996]
[0. 0.]
[0.        0.539645  0.0574087 0.0186567 0.0375702]
[0. 0. 0.]
[0.        0.780434  0.337956  0.0487407 0.0916433]
[0. 0.]
[0.       0.328511 0.348958 0.068287 0.109954]
[1. 1.]
[1.        0.164672  0.319481  0.0926418 0.190824 ]
[0. 0